# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'food.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Conn_database import *


userid = ''

class Ui_food_scr(object):
    def openwindow(self, food_scr, name):
        from login_ import Ui_login_scr
        self.d_window = QtWidgets.QMainWindow()
        self.UI = Ui_login_scr()
        self.UI.setupUi(self.d_window)
        user_name = userid
        if name == 'exit':
            from user_screen_ import Ui_user_scr
            self.b_window = QtWidgets.QMainWindow()
            self.ui = Ui_user_scr()
            self.ui.setupUi(self.b_window)
            self.b_window.show()
            food_scr.close()
        elif name == 'breakfast':
            receipt = generate_reciept(user_name, 'breakfast')
            from login_ import Ui_login_scr
            from receipt_ import Ui_receipt_window
            self.b_window = QtWidgets.QMainWindow()
            self.ui = Ui_receipt_window()
            self.ui.setupUi(self.b_window)
            self.ui.name_blank.setText(receipt[0])
            self.ui.id_blank.setText(receipt[1])
            self.ui.day_blank.setText(receipt[2])
            self.ui.date_blank.setText(str(receipt[3]))
            self.ui.order_id_blank.setText(str(receipt[4]))
            self.ui.order_name_blank.setText(receipt[5])
            self.ui.food_items_blank.setText(receipt[6])
            self.ui.diet_target_blank.setText(receipt[7])
            self.ui.total_blank.setText(str(receipt[8]))
            self.ui.address_blank.setText(receipt[9])
            self.b_window.show()
            food_scr.close()
        elif name == 'lunch':
            receipt = generate_reciept(user_name, 'lunch')
            from receipt_ import Ui_receipt_window
            self.b_window = QtWidgets.QMainWindow()
            self.ui = Ui_receipt_window()
            self.ui.setupUi(self.b_window)
            self.ui.name_blank.setText(receipt[0])
            self.ui.id_blank.setText(receipt[1])
            self.ui.day_blank.setText(receipt[2])
            self.ui.date_blank.setText(str(receipt[3]))
            self.ui.order_id_blank.setText(str(receipt[4]))
            self.ui.order_name_blank.setText(receipt[5])
            self.ui.food_items_blank.setText(receipt[6])
            self.ui.diet_target_blank.setText(receipt[7])
            self.ui.total_blank.setText(str(receipt[8]))
            self.ui.address_blank.setText(receipt[9])
            self.b_window.show()
            food_scr.close()
        elif name == 'dinner':
            receipt = generate_reciept(user_name, 'dinner')
            from receipt_ import Ui_receipt_window
            self.b_window = QtWidgets.QMainWindow()
            self.ui = Ui_receipt_window()
            self.ui.setupUi(self.b_window)
            self.ui.name_blank.setText(receipt[0])
            self.ui.id_blank.setText(receipt[1])
            self.ui.day_blank.setText(receipt[2])
            self.ui.date_blank.setText(str(receipt[3]))
            self.ui.order_id_blank.setText(str(receipt[4]))
            self.ui.order_name_blank.setText(receipt[5])
            self.ui.food_items_blank.setText(receipt[6])
            self.ui.diet_target_blank.setText(receipt[7])
            self.ui.total_blank.setText(str(receipt[8]))
            self.ui.address_blank.setText(receipt[9])
            self.b_window.show()
            food_scr.close()


    def setupUi(self, food_scr):
        userid = ''
        food_scr.setObjectName("food_scr")
        food_scr.resize(400, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(food_scr.sizePolicy().hasHeightForWidth())
        food_scr.setSizePolicy(sizePolicy)
        food_scr.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(food_scr)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 401, 601))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.background.setFont(font)
        self.background.setStyleSheet("")
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("images/image_3.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.breakfast = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openwindow(food_scr, 'breakfast'))
        self.breakfast.setGeometry(QtCore.QRect(220, 300, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.breakfast.setFont(font)
        self.breakfast.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    border-radius: 20px;\n"
"    background-color: #fcf403;\n"
"    color: #d4d4cf;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.breakfast.setObjectName("breakfast")
        self.lunch = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openwindow(food_scr, 'lunch'))
        self.lunch.setGeometry(QtCore.QRect(220, 380, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lunch.setFont(font)
        self.lunch.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    border-radius: 20px;\n"
"    background-color: #4ae8a6;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.lunch.setObjectName("lunch")
        self.dinner = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openwindow(food_scr, 'dinner'))
        self.dinner.setGeometry(QtCore.QRect(220, 460, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dinner.setFont(font)
        self.dinner.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    border-radius: 20px;\n"
"    background-color: #f23838;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.dinner.setObjectName("dinner")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openwindow(food_scr, 'exit'))
        self.pushButton_4.setGeometry(QtCore.QRect(220, 520, 151, 41))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border: 0px;\n"
"    border-radius: 20px;\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: white;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        food_scr.setCentralWidget(self.centralwidget)

        self.retranslateUi(food_scr)
        QtCore.QMetaObject.connectSlotsByName(food_scr)

    def retranslateUi(self, food_scr):
        _translate = QtCore.QCoreApplication.translate
        food_scr.setWindowTitle(_translate("food_scr", "MainWindow"))
        self.breakfast.setText(_translate("food_scr", "BREAKFAST"))
        self.lunch.setText(_translate("food_scr", "LUNCH"))
        self.dinner.setText(_translate("food_scr", "DINNER"))
        self.pushButton_4.setText(_translate("food_scr", "EXIT"))
import app_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    food_scr = QtWidgets.QMainWindow()
    ui = Ui_food_scr()
    ui.setupUi(food_scr)
    food_scr.show()
    sys.exit(app.exec_())
