# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from user_screen_ import Ui_user_scr
from signup_sc_r_ import Ui_signup_scr

from Conn_database import *


class Ui_login_scr(object):
    def openwindow(self, btn_name, login_scr):
        if btn_name == 'user':
            userid = self.lineEdit.text() #fetching from username in app
            password = self.lineEdit_2.text()
            #crearing two functions here and call them inside if statements

            if login_attempt_user(userid,password) :
                import user_screen_
                self.l_window = QtWidgets.QMainWindow()
                self.ui = Ui_user_scr()
                self.ui.setupUi(self.l_window)
                user_screen_.userid = userid
                self.l_window.show()
                login_scr.close()
            elif login_attempt_trainer(userid,password):
                from trainer_ import Ui_MainWindow
                self.l_window = QtWidgets.QMainWindow()
                self.ui = Ui_MainWindow()
                self.ui.setupUi(self.l_window)
                trainer = trainer_info(self.lineEdit.text())
                self.ui.id_blank.setText(trainer[0])
                self.ui.name_blank.setText(trainer[1])
                self.ui.hire_blank.setText(trainer[2])
                self.ui.total_blank.setText(trainer[3])
                self.ui.salary_blank.setText(trainer[4])
                self.ui.wallet_blank.setText(trainer[5])
                self.l_window.show()
                login_scr.close()

        elif btn_name == 'sign':
            from signup_sc_r_ import Ui_signup_scr
            self.s_window = QtWidgets.QMainWindow()
            self.ui = Ui_signup_scr()
            self.ui.setupUi(self.s_window)
            self.s_window.show()
            login_scr.close()

    def setupUi(self, login_scr):
        login_scr.setObjectName("login_scr")
        login_scr.setEnabled(True)
        login_scr.resize(410, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login_scr.sizePolicy().hasHeightForWidth())
        login_scr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        login_scr.setFont(font)
        self.centralwidget = QtWidgets.QWidget(login_scr)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 190, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        font.setItalic(False)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 290, 301, 51))
        self.lineEdit.setStyleSheet("QLineEdit\n"
"{\n"
"     border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 360, 301, 51))
        self.lineEdit_2.setStyleSheet("QLineEdit\n"
"{\n"
"     border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.login = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openwindow('user', login_scr))
        self.login.setGeometry(QtCore.QRect(80, 440, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.login.setFont(font)
        self.login.setStyleSheet("QPushButton {\n"
"    border: 1px solid #8f8f91;\n"
"    border-radius: 20px;\n"
"    background-color: yellow;\n"
"    color: #bbbdbb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.login.setObjectName("login")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openwindow('sign', login_scr))
        self.pushButton_2.setGeometry(QtCore.QRect(80, 490, 251, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setKerning(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: 1px solid #8f8f91;\n"
"    border-radius: 20px;\n"
"    background-color: #03fc03;\n"
"    color: #bbbdbb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -70, 411, 361))
        self.label_2.setStyleSheet("opacity: 0.5")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/image_1.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 288, 411, 311))
        self.label_3.setStyleSheet("QLabel#label_3{\n"
"background-color: white;\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.warning = QtWidgets.QLabel(self.centralwidget)
        self.warning.setGeometry(QtCore.QRect(50, 250, 301, 20))
        self.warning.setText("")
        self.warning.setAlignment(QtCore.Qt.AlignCenter)
        self.warning.setObjectName("warning")
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.login.raise_()
        self.pushButton_2.raise_()
        self.warning.raise_()
        login_scr.setCentralWidget(self.centralwidget)

        self.retranslateUi(login_scr)
        QtCore.QMetaObject.connectSlotsByName(login_scr)

    def retranslateUi(self, login_scr):
        _translate = QtCore.QCoreApplication.translate
        login_scr.setWindowTitle(_translate("login_scr", "MainWindow"))
        self.label.setText(_translate("login_scr", "ATHLEAN FIT"))
        self.lineEdit.setPlaceholderText(_translate("login_scr", "Username"))
        self.lineEdit_2.setPlaceholderText(_translate("login_scr", "Password"))
        self.login.setText(_translate("login_scr", "LOG IN"))
        self.pushButton_2.setText(_translate("login_scr", "Sign Up"))
import app_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_scr = QtWidgets.QMainWindow()
    ui = Ui_login_scr()
    ui.setupUi(login_scr)
    login_scr.show()
    sys.exit(app.exec_())
