# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Conn_database import *

userid = ''

class Ui_user_scr(object):
    def openwindow(self, user_scr, name, pass_id):
        if name == 'exit':
            from login_ import Ui_login_scr
            self.b_window = QtWidgets.QMainWindow()
            self.ui = Ui_login_scr()
            self.ui.setupUi(self.b_window)
            self.b_window.show()
            user_scr.close()
        elif name == 'order':
            import food_
            from food_ import Ui_food_scr
            self.f_window = QtWidgets.QMainWindow()
            self.ui = Ui_food_scr()
            self.ui.setupUi(self.f_window)
            food_.userid = pass_id
            self.f_window.show()
            user_scr.close()
        elif name == 'work':
            from workout_ import Ui_workout_window
            self.f_window = QtWidgets.QMainWindow()
            self.ui = Ui_workout_window()
            self.ui.setupUi(self.f_window)
            workout = get_current_day_workout()
            self.ui.exercise_1.setText(workout[0])
            self.ui.exercise_2.setText(workout[1])
            self.ui.exercise_3.setText(workout[2])
            self.ui.exercise_4.setText(workout[3])
            self.f_window.show()
            user_scr.close()

    def setupUi(self, user_scr):
        user_scr.setObjectName("user_scr")
        user_scr.resize(409, 594)
        self.centralwidget = QtWidgets.QWidget(user_scr)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 411, 591))
        self.label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: #b32f2d;\n"
"}")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 19, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(18)
        font.setItalic(True)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"    color: white;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openwindow(user_scr, 'work', userid))
        self.pushButton.setGeometry(QtCore.QRect(100, 163, 201, 51))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid white;\n"
"    border-radius: 25px;\n"
"    background-color: #f5c20c;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openwindow(user_scr, 'order', userid))
        self.pushButton_2.setGeometry(QtCore.QRect(100, 253, 201, 51))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid white;\n"
"    border-radius: 25px;\n"
"    background-color: #37e310;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openwindow(user_scr, 'exit', userid))
        self.pushButton_3.setGeometry(QtCore.QRect(100, 350, 201, 51))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: 0px solid white;\n"
"    border-radius: 25px;\n"
"    background-color:#b32f2d;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:pressed \n"
"{\n"
"    color: white;    \n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        user_scr.setCentralWidget(self.centralwidget)

        self.retranslateUi(user_scr)
        QtCore.QMetaObject.connectSlotsByName(user_scr)

    def retranslateUi(self, user_scr):
        _translate = QtCore.QCoreApplication.translate
        user_scr.setWindowTitle(_translate("user_scr", "MainWindow"))
        self.label_2.setText(_translate("user_scr", "Welcome"))
        self.pushButton.setText(_translate("user_scr", "WORK OUT"))
        self.pushButton_2.setText(_translate("user_scr", "ORDER FOOD"))
        self.pushButton_3.setText(_translate("user_scr", "LOG OUT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    user_scr = QtWidgets.QMainWindow()
    ui = Ui_user_scr()
    ui.setupUi(user_scr)
    print(userid)
    user_scr.show()
    sys.exit(app.exec_())
